spring:
    docker:
      compose:
        file: src/main/docker/compose.yaml
        enabled: true
        lifecycle-management: start_only

    liquibase:
      change-log: db/changelog/master.yaml
      enabled: true

